spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xcxy?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&utoRec&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8081
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl