version: "3"
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/wwwroot
  redis:
    image: redis
    container_name: docker_redis
    volumes:
      - ./redis/datadir:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      IP: "121.196.145.132"
      PORT: "3306"
      DRIVERCLASSNAME: "com.mysql.cj.jdbc.Driver"
      DBNAME: "activities"
      URL: "jdbc:mysql://121.196.145.132:3306/activities?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false"
      USERNAME: "root"
      PASSWORD: "123456"
    depends_on:
      - redis