spring:
  datasource:
    url: jdbc:mysql://121.196.145.132:3306/activities?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&utoRec&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/,classpath:/pub/,file:/uploads
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  redis:
    host: 121.196.145.132
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    password: 123456
server:
  port: 8081
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl